### ISSUE TITLE
Error when Playing

### ISSUE THREAD

**Issue by Adhil-Suresh** [MartinKral/Spherestroyer#2]
![Screenshot 2020-04-29 at 11 19 46 AM](https://user-images.githubusercontent.com/43722374/80564442-7460dd80-8a0b-11ea-874f-47b720389bb2.png)
How can resolve this error?
I tired with the same Unity version but still having this error.

**Comment by MartinKral** [comment]
Hello @Adhil-Suresh , sorry for the late reply.

Can you try with 2020.1.3?
